config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root to: "entries#index"

  resources :users, only: :show do
    resources :entries
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :blocks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :activities
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :entries

  has_many :activities
  has_many :blocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @entries = current_user.entries
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
    render :new, entry: @entry
  end

  def create
    entry = current_user.entries.create(entry_params)
    redirect_to action: :show, id: entry.id
  end

  def update
    entry = Entry.find(params[:id])
    if entry.update(entry_params)
      redirect_to action: :show, id: params[:id]
    else
      flash[:alert] = entry.errors.messages
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    entry = Entry.find(params[:id])
    entry.destroy!
    redirect_to action: :index
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/index.html.erb
<h1>Diary</h1>

<%= link_to 'New Entry', new_user_entry_path(current_user.id) %>

<%= content_tag :div,
  id: "data",
  entries: @entries.to_json do %>
<% end %>

app/views/entries/new.html.erb
<%= form_for [current_user, @entry] do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
    <%= f.text_area :body %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/entries/show.html.erb
<h1><%= @entry.title %></h1>
<%= link_to 'Edit entry', edit_user_entry_path(@entry.id) %>
<p><%= @entry.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <div id="app"></div>
  </body>
</html>